### PR TITLE
Tidying codebase to increase readability

### PR DESCRIPTION
**Pull request by Jabelpeeps**
Hi mcmonkey,

Long time no see.  Hope you are well.

As I think I mentioned somewhere or other, I've been learning Java - there are some of my other projects in my github if you are interested.

As you can see from the attached PR, I have embarked on a project to tidy up the sentry codebase.  This is not just reformatting for clarity, but also adding some comments to document the code as I go through.  

Following on from there I'm hoping to be able to add/fix a few features, but - as you once said (afairc) - this is pretty much impossible with the code in it's current state.

I'm not done yet by a long shot, but I thought I'd submit a PR to start the conversation with you, to see what your thoughts are on what I am doing.

regards

Jabel.

### CODE REVIEW

**Comment by mcmonkey4eva** [comment]
A lot of the formatting seems a bit off...
EG you have
`BodyguardTeleportStuckAction( SentryInstance inst, Sentry plugin ){`
which should be
`BodyguardTeleportStuckAction(SentryInstance inst, Sentry plugin) {`

You're pretty much adding spaces everywhere but where they belong :/

Check out https://google-styleguide.googlecode.com/svn/trunk/javaguide.html or http://www.oracle.com/technetwork/java/javase/documentation/codeconvtoc-136057.html for some of the common standards in Java formatting.

Additionally, check out Denizen or Citizens2 source code for some mostly quality code format.

(If you're using IntelliJ you can configure a little and then press a button to autoformat an entire codebase at once. Pretty useful!)

A few standards our team generally follows that are less common in the Java world (IE, are probably not in the links above):
No `} else {` -> that should be two lines.
Use `{ braces }` wherever they fit. EG `if (x) y();` shouldn't be used, it should be a braced block.



Anyway, I very much appreciate the effort to clean up this nightmare. I originally didn't do it myself because the original author (Jrbudda) would come back and yell at me if I tried. He seems to be entirely gone now, so no harm in cleaning things up.


If I were you, I'd try this process:
1: Use an automated utility to clean the code (Again, IntelliJ can do this with only minor configuration)
2: Add comments however and wherever you think is useful
3: Add features as needed
4: Use the automated utility again before committing just to ensure everything's formatted cleanly.


Also, I'm not sure what you're using as a setup, but I'd highly recommend a proper IDE and desktop git client (EG Github-for-windows or whatever) rather than using the web editor (Which it looks like you might be doing, as I've only seen the web editor have commit titles / organization like that)

**Comment by Jabelpeeps** [comment]
Hey, thanks for getting back.

You are correct, so far I have merely been editing the files on github, though I have kept away from the big ones as yet.  The current spacing probably doesn't meet anybody's guidelines, but imho the code was badly in need of some 'daylight' in order to help (me) with reading it.  I wasn't going to leave it like that - as I already knew about automatic re-formatting - but as an intermediate stage it is helpful to me, and should affect how the code compiles.

Getting an IDE setup was one of the things I was hoping to ask you about.  I have both Eclipse and Android Studio on this laptop (but not the pure IntelliJ), they can both do auto-formatting as you describe, but what I struggled to figure out last time I tried (admittedly some months back in my Java journey) was how to setup the dependencies, etc so that I could actually get the plugin to compile.

I've dabbled with maven, but have mainly used Gradle, as both Android Studio and the game framework (libGDX) I have been using favour Gradle for their dependency management.

**Comment by mcmonkey4eva** [comment]
In theory, it should be as easy as:

- Install IntelliJ
- Locally compile Spigot (Using buildtools, it's all automatic)
- Import the pom.xml into IntelliJ
- Press the green arrow lookin' build button

And... boom, you got compiled files :D 

Half the dependencies are even local files (included in the `lib/` folder) so it should be super easy to handle Sentry compiling even if you don't use maven for it.

**Comment by Jabelpeeps** [comment]
Hi,

I'm back on this, and thought I'd send you a message to alert you to the fact.

I know the formatting doesn't meet your approval, but if you can look past that, I'd be interested on you comments regarding the other changes I have made/am making.

regards

**Comment by Jabelpeeps** [comment]
I guess you're never going to respond to this PR.

**Comment by mcmonkey4eva** [comment]
@Jabelpeeps oh sorry I didn't realize you were still working on this.
Sentry has ceased as a project :/
We (the Citizens team) now use and advocate Sentinel: https://github.com/mcmonkey4eva/Sentinel/blob/master/README.md
Much cleaner code, much better functioning code, etc.

**Comment by Jabelpeeps** [comment]
@mcmonkey4eva 
"Sentry has ceased as a project :/"
I take it this means you have ceased working on it (as a project)?
Do you have any objections if I continue on with it?

**Comment by mcmonkey4eva** [comment]
@Jabelpeeps Yes I have objections. It's a pile of crap that's been replaced with not-crap.

if you want to help the community, contribute to Sentinel.

**Comment by Jabelpeeps** [comment]
@mcmonkey4eva said "if you want to help the community, contribute to Sentinel."
This line of your reads like an accusation;  whether this is what you were intending to convey, I feel that I must record that I thought I was contributing to the community with what I was doing here with Sentry.  

I sent you this PR to let you know what I was doing, and you seemed to appreciate it (ref the third to last paragraph of your comment on 30th Aug '15).  I therefore assumed that you continued to be aware of what I was doing, and just too busy to respond. 

I now find out that you had forgotten about my work and started Sentinel just over 1 month ago (when the majority of the commits here were already made), and then declared that "Sentry has ceased".  Do you understand why I might be a bit peeved about this?

If you care to look at my fork, you can see that I have now contributed more lines to it than jrbudda, and made extensive changes to many elements - many of which I believe have increased the performance of the code, as well as clarifying it, and making it easier to work with in the future - and I would like to continue with this work for my own reasons.

I would have liked to have worked with you on this project, and benefitted from your experience writing plugins, however I am not willing to do this at the cost of abandoning the work I have done here, hence my wish to continue with Sentry.  I don't have any expectation that you will make any further contributions - given that you have something else to focus on - so if you wish to pass on the ownership of the Sentry repository to me that would be ok with me.

Obviously I don't know what your plans are for the future of Sentinel, but as things stand Sentry and Sentinel have different feature sets, and there may well be room for them both to exist within the space of combat npc plugins - and maybe even benefit each other, and/or work well together in the future.  Stranger things have happened...

**Pull request closed without merging**
